# Conexión directa al nuevo puerto 5435 y nuevo usuario
spring.datasource.url=jdbc:postgresql://localhost:5435/monitoreo_estres_db
spring.datasource.username=admin_ito
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true